version: '3'
services:
  anitrend-edge:
    image: ghcr.io/anitrend/on-the-edge:latest
    container_name: anitrend-edge
    networks:
      - default
    env_file: .env

networks:
  default:
    name: traefik
    external: true
