version: '3'
services:
  anitrend-edge:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["/usr/app/server", "--allow-all"]
    container_name: anitrend-edge
    networks:
      - default
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anitrend-edge.rule=Host(`anitrend.edge.localhost`)"
      - "traefik.http.routers.anitrend-edge.entrypoints=web,websecure"
      - "traefik.http.routers.anitrend-edge.service=anitrend-edge"
      - "traefik.http.routers.anitrend-edge.tls=true"
      - "traefik.http.routers.anitrend-edge.tls.certresolver=staging"
      - "traefik.http.services.anitrend.loadbalancer.server.port=8888"

networks:
  default:
    name: traefik
    external: true
