version: '3'
services:
  anitrend-edge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anitrend-edge
    networks:
      - default
    env_file: .env
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.anitrend-edge.rule=Host(`${HOST}`)"
      - "traefik.http.routers.anitrend-edge.entrypoints=web,websecure"
      - "traefik.http.routers.anitrend-edge.service=anitrend-edge"
      - "traefik.http.routers.anitrend-edge.tls=true"
      - "traefik.http.routers.anitrend-edge.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.services.anitrend-edge.loadbalancer.server.port=${PORT}"
    restart: unless-stopped

networks:
  default:
    name: traefik
    external: true
