# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: deno-test

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Load properties file
        run: |
          declare -A properties
          while IFS='=' read -r key value; do
            properties["$key"]="$value"
          done < supabase/.env.defaults

          for key in "${!properties[@]}"; do
            echo "::set-env name=$key::${properties[$key]}"
          done

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
