name: deno-verify

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2

      - name: Run deno linter
        run: deno lint

      - name: Run deno checks
        run: deno task check
