name: supabase-deploy

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.28.3

      - run: supabase functions deploy config --project-ref $PROJECT_ID
      - run: supabase functions deploy news-sync --project-ref $PROJECT_ID
      - run: supabase functions deploy news --project-ref $PROJECT_ID
      - run: supabase functions deploy series --project-ref $PROJECT_ID
